on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
jobs:
  test:
    strategy:
      matrix:
        runs-on:
          - ubuntu-22.04
          - macos-13
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V28
      - uses: ./
      - run: actionlint
      - run: shellcheck nix-develop-gha.sh
  test-determinate:
    strategy:
      matrix:
        runs-on:
          - ubuntu-22.04
          - macos-13
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: ./
      - run: actionlint
      - run: shellcheck nix-develop-gha.sh
